Repository UMC-7th-Peekle/peekle-api-server, pull requests merged in 2025-01, with the labels that each got.

#33 Feature/30 multer
  index.js
  middleware/uploader.js
  models/database/Events.js
  models/database/UserOauth.js
  package.json
  routes/test.router.js
  utils/errors/errors.js
  utils/trash/README.md
  utils/trash/check.s3.connection.js
  utils/trash/uploader.controller.js
  utils/upload/uploader.object.js
Labels: :sparkles: Features

#31 [이안] Event MVP
  controllers/events/crud.events.controller.js
  controllers/events/read.events.controller.js
  controllers/events/report.events.controller.js
  controllers/events/scrap.events.controller.js
  models/database/EventScraps.js
  models/database/Reports.js
  package-lock.json
  package.json
  routes/events.router.js
  services/events/crud.events.service.js
  services/events/read.events.service.js
  services/events/report.events.service.js
  services/events/scrap.events.service.js
Labels: :sparkles: Features

#36 Community 관련 리팩토링
  controllers/community/article.crud.community.contoller.js
  controllers/community/article.like.community.controller.js
  controllers/community/article.read.community.controller.js
  controllers/community/comment.community.contorller.js
  controllers/community/comment.like.community.controller.js
  middleware/authenticate.jwt.js
  models/index.js
  routes/community.router.js
  routes/test.router.js
  services/auth/login.auth.service.js
  services/community/article.crud.community.service.js
  services/community/article.like.community.service.js
  services/community/article.read.community.service.js
  services/community/comment.community.service.js
  services/community/comment.like.community.service.js
  utils/tokens/create.jwt.tokens.js
Labels: :recycle: Refactor

#48 [재민] Feat: 댓글 조회 기능
  controllers/community/comment.community.contorller.js
  routes/community.router.js
  services/community/comment.community.service.js
Labels: :sparkles: Features

#42 [재민] Feat: 게시글 관련 사진 파일 업로드
  controllers/community/article.crud.community.contoller.js
  routes/community.router.js
  services/community/article.crud.community.service.js
Labels: :sparkles: Features

#50 [재민] Feat: 게시글 신고 기능
  controllers/community/article.report.community.controller.js
  routes/community.router.js
  services/community/article.report.community.service.js
Labels: :sparkles: Features

#53 [재민] Feat: 댓글 신고 기능
  controllers/community/comment.report.community.controller.js
  routes/community.router.js
  services/community/comment.report.community.service.js
Labels: :sparkles: Features

#60 Feat: 사진 정보 가져올 때 base url 붙이는 함수 구현
  services/community/article.crud.community.service.js
  utils/upload/uploader.object.js
Labels: :sparkles: Features

#66 Feat: 커뮤니티 인기글 집계 기능
  controllers/community/article.aggregate.community.contoller.js
  routes/community.router.js
  services/community/article.aggregate.community.service.js
Labels: :sparkles: Features

#72 Fix: 커뮤니티 자잘한 오류 해결
  controllers/community/article.aggregate.community.controller.js
  controllers/community/article.crud.community.controller.js
  controllers/community/comment.community.controller.js
  controllers/events/create.events.controller.js
  controllers/events/list.events.controller.js
  middleware/validate.js
  routes/community.router.js
  routes/events.router.js
  services/community/article.aggregate.community.service.js
  services/community/article.crud.community.service.js
  services/community/article.read.community.service.js
  services/community/comment.community.service.js
  services/events/list.events.service.js
  utils/errors/errors.js
Labels: :lady_beetle: Bug

#73 Feat: 접수된 신고 사항 조회 및 사용자 제재 관련 처리
  controllers/admin/report.list.admin.controller.js
  controllers/admin/report.manage.admin.controller.js
  controllers/auth/register.auth.controller.js
  index.js
  models/database/EventLocationGroups.js
  models/database/Events.js
  models/database/UserRestrictions.js
  models/database/init-models.js
  models/index.js
  package-lock.json
  package.json
  routes/admin.router.js
  routes/auth.router.js
  services/admin/report.list.admin.service.js
  services/admin/report.manage.admin.service.js
  services/auth/register.auth.service.js
  utils/docker/mongodb-docker/docker-compose.yaml
  utils/logger/logger.js
  utils/trash/check.s3.connection.js
  utils/trash/redis.transport.js
  utils/trash/uploader.controller.js
Labels: :sparkles: Features

#74 Feat: 약관 관련 CRUD
  controllers/admin/terms.admin.controller.js
  controllers/events/list.events.controller.js
  routes/admin.router.js
  services/admin/terms.admin.service.js
  services/events/list.events.service.js
  utils/logger/logger.js
Labels: :sparkles: Features

#79 Feat: 공지사항 생성, 수정, 삭제
  controllers/notices/cud.notices.controller.js
  middleware/uploader.js
  middleware/validate.js
  models/database/NoticeImages.js
  models/index.js
  package-lock.json
  package.json
  routes/notices.router.js
  services/community/article.crud.community.service.js
  services/events/detail.events.service.js
  services/notices/cud.notices.service.js
  utils/logger/logger.js
  utils/upload/uploader.object.js
Labels: :sparkles: Features

#78 Feat: 공지사항 조회 관련
  controllers/notices/read.notices.controller.js
  index.js
  routes/notices.router.js
  services/notices/read.notices.service.js
Labels: :sparkles: Features

#82 community 검수
  controllers/auth/kakao.auth.controller.js
  controllers/community/article.aggregate.community.controller.js
  controllers/community/article.crud.community.controller.js
  controllers/community/article.like.community.controller.js
  controllers/community/article.read.community.controller.js
  controllers/community/article.report.community.controller.js
  controllers/community/comment.community.controller.js
  controllers/community/comment.like.community.controller.js
  controllers/community/comment.report.community.controller.js
  controllers/community/report.community.controller.js
  controllers/events/list.events.controller.js
  middleware/uploader.js
  middleware/validate.js
  models/database/Communities.js
  models/database/NoticeImages.js
  models/index.js
  routes/community.router.js
  services/auth/phone.auth.service.js
  services/community/article.aggregate.community.service.js
  services/community/article.crud.community.service.js
  services/community/article.read.community.service.js
  services/community/article.report.community.service.js
  services/community/comment.community.service.js
  services/community/report.community.service.js
  services/events/list.events.service.js
  utils/cipher/encrypt.js
  utils/handlers/error.logger.js
  utils/logger/logger.js
  utils/sms/coolsms.js
  utils/validators/auth/auth.validators.js
  utils/validators/community/article.validators.js
Labels: :recycle: Refactor
