Repository UMC-7th-Peekle/peekle-api-server, pull requests merged in 2025-02, with the labels that each got.

#92 이벤트 조회 쿼리 + 찜한 이벤트 목록 조회
  controllers/events/groups.events.controller.js
  controllers/events/list.events.controller.js
  controllers/events/scrap.events.controller.js
  routes/events.router.js
  services/events/list.events.service.js
  services/events/scrap.events.service.js
Labels: :recycle: Refactor

#100 커뮤니티 Swagger
  routes/community.router.js
  routes/swagger.index.js
  utils/validators/community/article.validators.js
Labels: :page_with_curl: Docs

#98 공지사항 swagger
  controllers/events/detail.events.controller.js
  routes/events.router.js
  routes/notices.router.js
  routes/swagger.index.js
  services/events/scrap.events.service.js
  services/notices/cud.notices.service.js
Labels: :page_with_curl: Docs

#97 이벤트 swagger
  routes/events.router.js
  routes/swagger.index.js
Labels: :page_with_curl: Docs

#110 Test: Community 테스트 코드 작성
  __tests__/article.aggregate.community.test.js
  __tests__/article.crud.community.test.js
  __tests__/article.like.community.test.js
  __tests__/article.read.community.test.js
  __tests__/comment.community.test.js
  __tests__/comment.like.community.test.js
  __tests__/report.community.test.js
  __tests__/sample.test.js
  babel.config.json
  index.js
  jest.config.js
  package-lock.json
  package.json
  services/community/article.crud.community.service.js
  services/community/article.read.community.service.js
  services/community/comment.community.service.js
  services/community/report.community.service.js
  utils/path.util.js
Labels: :white_check_mark: Test

#111 Feat: 게시글 및 댓글 익명 처리
  __tests__/article.aggregate.community.test.js
  __tests__/article.crud.community.test.js
  __tests__/article.read.community.test.js
  __tests__/comment.community.test.js
  services/community/article.aggregate.community.service.js
  services/community/article.crud.community.service.js
  services/community/article.read.community.service.js
  services/community/comment.community.service.js
Labels: :sparkles: Features

#120 Tickets API
  controllers/events/detail.events.controller.js
  controllers/tickets/create.tickets.controller.js
  controllers/tickets/detail.tickets.controller.js
  controllers/tickets/list.tickets.controller.js
  middleware/uploader.js
  models/database/Tickets.js
  routes/tickets.router.js
  services/tickets/create.tickets.service.js
  services/tickets/detail.tickets.service.js
  services/tickets/list.tickets.service.js
  utils/validators/tickets/tickets.validators.js
Labels: :sparkles: Features

#125 이벤트, 티켓 부분 리펙토링
  controllers/events/create.events.controller.js
  controllers/events/detail.events.controller.js
  controllers/events/groups.events.controller.js
  controllers/events/list.events.controller.js
  controllers/events/report.events.controller.js
  controllers/events/scrap.events.controller.js
  controllers/tickets/create.tickets.controller.js
  controllers/tickets/detail.tickets.controller.js
  controllers/tickets/list.tickets.controller.js
  routes/tickets.router.js
  services/events/category.events.service.js
  services/events/create.events.service.js
  services/events/detail.events.service.js
  services/events/list.events.service.js
  services/events/report.events.service.js
  services/events/scrap.events.service.js
  services/tickets/create.tickets.service.js
  services/tickets/detail.tickets.service.js
  services/tickets/list.tickets.service.js
  utils/validators/tickets/tickets.validators.js
Labels: :recycle: Refactor

#126 커뮤니티, 공지사항(조회), Admin 관련 점검
  __tests__/comment.like.community.test.js
  controllers/community/article.crud.community.controller.js
  controllers/community/report.community.controller.js
  services/community/article.crud.community.service.js
  services/community/article.like.community.service.js
  services/community/article.read.community.service.js
  services/community/comment.like.community.service.js
  services/community/report.community.service.js
Labels: :recycle: Refactor

#132 이벤트 조회할 때 위치 좌표도 같이 조회하도록 수정
  .gitignore
  config/config.js
  config/ecosystem.config.cjs
  config/jest.config.js
  controllers/auth/kakao.auth.controller.js
  controllers/events/create.events.controller.js
  index.js
  middleware/README.md
  middleware/authenticate.jwt.js
  middleware/validate.js
  models/README.md
  models/auto.setting.sequelize.cjs
  models/database/ArticleComments.js
  models/database/EventLocation.js
  models/database/Events.js
  models/database/init-models.js
  models/index.js
  models/seed/data.js
  models/sql/2025-02-11/before.event.change.sql
  package-lock.json
  package.json
  services/auth/kakao.auth.service.js
  services/events/create.events.service.js
  services/events/detail.events.service.js
  services/events/list.events.service.js
  services/users/profile.users.service.js
  utils/cipher/encrypt.js
  utils/handlers/jwt.handlers.js
  utils/logger/logger.js
  utils/options/options.js
  utils/sms/coolsms.js
  utils/swagger/options.js
  utils/tokens/create.jwt.tokens.js
  utils/upload/uploader.object.js
  utils/validators/events/events.validators.js
Labels: :recycle: Refactor

#141 게시글 수정 익명 여부 수정 추가
  services/community/article.crud.community.service.js
Labels: :lady_beetle: Bug

#142 티켓 검토 + 이벤트 스크랩 수정
  controllers/events/scrap.events.controller.js
  controllers/tickets/detail.tickets.controller.js
  services/events/list.events.service.js
  services/events/scrap.events.service.js
  services/tickets/detail.tickets.service.js
  services/tickets/list.tickets.service.js
Labels: :recycle: Refactor

#163 커뮤니티 건의하기 요청 항목 수정
  controllers/community/article.crud.community.controller.js
  models/database/CommunitySuggestions.js
  models/database/PeeklingChatroom.js
  models/database/PeeklingChats.js
  models/database/init-models.js
  services/community/article.crud.community.service.js
  utils/validators/community/article.validators.js
Labels: :recycle: Refactor

#167 Community: 탈퇴 사용자 처리
  controllers/community/article.aggregate.community.controller.js
  controllers/community/article.read.community.controller.js
  routes/community.router.js
  services/community/article.aggregate.community.service.js
  services/community/article.read.community.service.js
  services/community/comment.community.service.js
Labels: :sparkles: Features
